---
# This role contains tasks for checking security on target server

- name: Check for PermitRootLogin no
  command: grep -q '^PermitRootLogin no' /etc/ssh/sshd_config
  register: permit_root_login
  ignore_errors: true

- name: Check for PasswordAuthentication no
  command: grep -q '^PasswordAuthentication no' /etc/ssh/sshd_config
  register: password_authentication
  ignore_errors: true

- name: Check for PubkeyAuthentication yes
  command: grep -q '^PubkeyAuthentication yes' /etc/ssh/sshd_config
  register: pubkey_authentication
  ignore_errors: true

- name: Warn if PermitRootLogin no is not found
  debug:
    msg:
      - " -----------------------------------------  W A R N I N G  --------------------------------------------- "
      - "'PermitRootLogin no' is not set in /etc/ssh/sshd_config, play this role with tag 'harden' to add the line"
  when: permit_root_login.rc != 0

- name: Warn if PasswordAuthentication no is not found
  debug:
    msg:
      - " ----------------------------------------------  W A R N I N G  ----------------------------------------------- "
      - "'PasswordAuthentication no' is not set in /etc/ssh/sshd_config, play this role with tag 'harden' to add the line"
  when: password_authentication.rc != 0

- name: Warn if PubkeyAuthentication yes is not found
  debug:
    msg:
      - " ----------------------------------------------  W A R N I N G  ---------------------------------------------- "
      - "'PubkeyAuthentication yes' is not set in /etc/ssh/sshd_config, play this role with tag 'harden' to add the line"
  when: pubkey_authentication.rc != 0

- name: Configure sshd_config
  lineinfile:
    regex: "{{ item.value }}"
    line: "{{ item.key }}"
    path: /etc/ssh/sshd_config
  loop: "{{ conf_lines | dict2items }}"
  vars:
    conf_lines:
      "PermitRootLogin no": "^#?PermitRootLogin" 
      "PasswordAuthentication no": "^#?PasswordAuthentication" 
      "PubkeyAuthentication yes": "^#?PubkeyAuthentication" 
  become: yes
  notify:
    - restart sshd
  tags:
    - harden
    - never
